resources:
  repositories:
  - repository: 'templates'
    type: 'github'
    name: 'hizrael/test.template'
    endpoint: 'https://github.com/hizrael/test.template.git'
jobs: templates/build.steps.yml

