name: $(TeamProject)_$(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

# do not build PRs
pr: none
# do not build tags
trigger:
  branches:
    include:
    - refs/*
    exclude:
    - refs/tags/*

steps:
- powershell: |
    & setx TestVar2 123456 /M

- powershell: Write-Host "TestVar2=${env:TestVar2}"
