name: $(TeamProject)_$(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

# do not build PRs
pr: none
# do not build tags
trigger:
  branches:
    include:
    - refs/*
    exclude:
    - refs/tags/*
variables:
  ElementsForA: 'Four'
  ElementsForB: 'Five'

jobs:
- job: CreateVariables
  steps:
  - powershell: |
      nvm
      return
      Write-Host 'Removing AzureRM'
      '[A]zureRM','[A]zureRM.*' | Remove-Module 
      Write-Host 'Trying Get-Module'
      Get-Module 'Az' -ListAvailable -ErrorAction SilentlyContinue | ? { ([version]::Parse($_.Version)).Major -eq 6 } | Select -First 1
      Write-Host 'Trying Get-InstalledModule'
      Get-InstalledModule 'Az' -ErrorAction SilentlyContinue | ? { ([version]::Parse($_.Version)).Major -eq 6 } | Select -First 1
      Write-Host 'Trying import'
      Import-Module -Name 'Az'
      Write-Host 'Finished import'
      Write-Log "The following modules are loaded:`n$(Get-Module ('Az*') | Select Name,Version -Unique | Sort Name | Out-String)"
