resources:
  repositories:
  - repository: 'templates'
    type: 'github'
    name: 'haimizrael/test.template'
    endpoint: 'haimizrael'
#jobs:
#- template: build.steps.yml@templates
variables:
  testvar: valueinyml

steps:
#- powershell: Get-WmiObject -Class Win32_Product  | Sort-Object  -Property Name
- powershell: Write-Host "publishPackagesOnBuild value is $($env:publishPackagesOnBuild)"
- powershell: Write-Host "publishPackagesOnBuild value is $(publishPackagesOnBuild)"

