name: $(TeamProject)_$(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

resources:
  repositories:
  - repository: 'templates'
    type: 'github'
    name: 'haimizrael/test.template'
    endpoint: 'haimizrael'
#jobs:
#- template: build.steps.yml@templates

steps:
#- powershell: Get-WmiObject -Class Win32_Product  | Sort-Object  -Property Name
- powershell: |
    $pref='Variable'; $v = "'`$(${pref}A)`"; iex $v
    "Write-Host '`$(${pref}A)','`$(${pref}B)'" | Out-File (Join-Path '$(Agent.TempDirectory)' 'test.ps1')

- powershell:
  targetType: 'filepath'
  filePath: (Join-Path '$(Agent.TempDirectory)' 'test.ps1')
