name: $(TeamProject)_$(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

# do not build PRs
pr: none
# do not build tags
trigger:
  branches:
    include:
    - refs/*
    exclude:
    - refs/tags/*
variables:
  ElementsForA: 'Four'
  ElementsForB: 'Five'

jobs:
- job: CreateVariables
  steps:
  - powershell: cmd /c where 7z.exe
  - powershell: gci env:;Invoke-WebRequest -useb -uri 'https://dev.azure.com/gcmlp/Test/_apis/build/definitions'
  - powershell: Write-Host "##vso[task.setvariable variable=localsecret;isOutput=true]$(secret)"
- template: steps.yml
