name: $(TeamProject)_$(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

# do not build PRs
pr: none
# do not build tags
trigger:
  branches:
    include:
    - refs/*
    exclude:
    - refs/tags/*
variables:
  ElementsForA: 'Four'
  ElementsForB: 'Five'

jobs:
- job:
  steps:
  - powershell: Write-Host "##vso[task.setvariable variable=localsecret]$(secret)"
- template: steps.yml
