name: $(TeamProject)_$(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

# do not build PRs
pr: none
# do not build tags
trigger:
  branches:
    include:
    - refs/*
    exclude:
    - refs/tags/*
  
steps:
- powershell: |
    '##vso[task.setvariable variable=TestVar2]123456'

- powershell: Write-Host "TestVar2=${env:TestVar2}"
