name: $(TeamProject)_$(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

# do not build PRs
pr: none
# do not build tags
trigger:
  branches:
    include:
    - refs/*
    exclude:
    - refs/tags/*
variables:
  ElementsForA: 'Four'
  ElementsForB: 'Five'

steps:
- template: steps.yml
  parameters:
    elements: variables['ElementsFor*']
