name: $(TeamProject)_$(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

# do not build PRs
pr: none
# do not build tags
trigger:
  branches:
    include:
    - refs/*
    exclude:
    - refs/tags/*
variables:
  ElementsForA: 'Four'
  ElementsForB: 'Five'

jobs:
- job: CreateVariables
  steps:
  - powershell: |
      $env:PSModulePath = "'C:\Modules';$($env:PSModulePath)"
      Write-Host 'Trying Get-Module'
      Get-Module 'Az' -ListAvailable -ErrorAction SilentlyContinue | ? { ([version]::Parse($_.Version)).Major -eq 6 } | Select -First 1
      Write-Host 'Trying Get-InstalledModule'
      Get-InstalledModule 'Az' -ErrorAction SilentlyContinue | ? { ([version]::Parse($_.Version)).Major -eq 6 } | Select -First 1
      Write-Host 'Contents'
      gci 'C:\Modules\az_6.1.0'
      Write-Host 'Trying install'
      Install-Module -Name 'Az' -Repository 'C:\Modules'
      Write-Host 'Finished install'
