resources:
  repositories:
  - repository: 'templates'
    type: 'github'
    name: 'haimizrael/test.template'
    endpoint: 'https://github.com/haimizrael/test.git'
jobs:
- template: templates/build.steps.yml
