name: $(TeamProject)_$(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

resources:
  repositories:
  - repository: 'templates'
    type: 'github'
    name: 'haimizrael/test.template'
    endpoint: 'haimizrael'
#jobs:
#- template: build.steps.yml@templates

steps:
#- powershell: Get-WmiObject -Class Win32_Product  | Sort-Object  -Property Name
- powershell: |
    $pref='Variable'; $v = "$(${pref}A)"; Write-Host "v=$v"
    $v2 = "$(${pref}B)"; Write-Host "v2=$v2"


