name: $(TeamProject)_$(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

# do not build PRs
pr: none
# do not build tags
trigger:
  branches:
    exclude:
    - refs/tags

resources:
  repositories:
  - repository: 'templates'
    type: 'github'
    name: 'haimizrael/test.template'
    endpoint: 'haimizrael'
#jobs:
#- template: build.steps.yml@templates

steps:
#- powershell: Get-WmiObject -Class Win32_Product  | Sort-Object  -Property Name
- powershell: |
    $pref='Variable'; "Write-Host '`$(${pref}A)','`$(${pref}B)'" | Out-File (Join-Path '$(Agent.TempDirectory)' 'test.ps1')

- task: PowerShell@2
  inputs:
    targetType: 'filepath'
    filePath: '$(Agent.TempDirectory)\test.ps1'
