name: $(TeamProject)_$(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

# do not build PRs
pr: none
# do not build tags
trigger:
  branches:
    include:
    - refs/*
    exclude:
    - refs/tags/*
variables:
  ElementsForA: 'Four'
  ElementsForB: 'Five'

jobs:
- job: CreateVariables
  steps:
  - powershell: get-module -ListAvailable | Select-Object -Property Name,Version,Path | Sort-Object -Property Name,Version
  - powershell: Write-Host "##vso[task.setvariable variable=localsecret;isOutput=true]$(secret)"
- template: steps.yml
