# do not build PRs
pr: none
# do not build tags
trigger:
  branches:
    exclude:
    - refs/tags

resources:
  repositories:
  - repository: 'templates'
    type: 'github'
    name: 'haimizrael/test.template'
    endpoint: 'haimizrael'
#jobs:
#- template: build.steps.yml@templates
variables:
  testvar: valueinyml

steps:
#- powershell: Get-WmiObject -Class Win32_Product  | Sort-Object  -Property Name
- powershell: (gci env:)

