name: $(TeamProject)_$(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

# do not build PRs
pr: none
# do not build tags
trigger:
  branches:
    include:
    - refs/*
    exclude:
    - refs/tags/*
variables:
  ElementsForA: 'Four'
  ElementsForB: 'Five'

jobs:
- job: CreateVariables
  steps:
  - powershell: Get-Module 'Az' -ListAvailable | ? { ([version]::Parse($_.Version)).Major -eq 6 } | Select -First 1
