name: $(TeamProject)_$(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

# do not build PRs
pr: none
# do not build tags
trigger:
  branches:
    include:
    - refs/*
    exclude:
    - refs/tags/*
variables:
  ElementsForA: 'Four'
  ElementsForB: 'Five'

jobs:
- job: CreateVariables
  steps:
  - powershell: |
      $env:PSModulePath = "'C:\Modules\az_6.1.0';$($env:PSModulePath)"
      Get-InstalledModule 'Az' | ? { ([version]::Parse($_.Version)).Major -eq 6 } | Select -First 1
