resources:
  repositories:
  - repository: 'templates'
    type: 'github'
    name: 'haimizrael/test.template'
    endpoint: 'haimizrael'
#jobs:
#- template: build.steps.yml@templates
steps:
- powershell: Test-Path 'HKCU:\SOFTWARE\Microsoft\CosmosDBEmulator'

